from pathlib import Path
from datetime import datetime, timedelta
import pandas as pd


# ============================================================
# AIRFAREX - VALID FARE SEARCH QUEUE GENERATOR
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent

# Input: DGCA routes generated by the route pipeline
INPUT_FILE = PROJECT_DIR / "DGCA" / "dgca_routes.csv"

# Output: valid future fare-search jobs
OUTPUT_FILE = BASE_DIR / "airfarex_valid_fare_search_queue.csv"

# Search dates relative to TODAY
SEARCH_WINDOWS = [1, 7, 15, 30, 45]

# DGCA frequency convention:
# 1 = Monday
# 2 = Tuesday
# 3 = Wednesday
# 4 = Thursday
# 5 = Friday
# 6 = Saturday
# 7 = Sunday


# ============================================================
# DATE PARSER
# ============================================================

def parse_date(value):
    """
    Parse DGCA dates safely.

    DGCA schedule dates are generally day-first.
    """
    if pd.isna(value):
        return None

    value = str(value).strip()

    if not value:
        return None

    parsed = pd.to_datetime(
        value,
        dayfirst=True,
        errors="coerce"
    )

    if pd.isna(parsed):
        return None

    return parsed.date()


# ============================================================
# FREQUENCY PARSER
# ============================================================

def parse_frequency(value):
    """
    Convert DGCA frequency into a set of weekday numbers.

    Example:
        '1234567' -> every day
        '135'     -> Monday, Wednesday, Friday
    """

    if pd.isna(value):
        return set()

    value = str(value).strip()

    weekdays = set()

    for character in value:
        if character in "1234567":
            weekdays.add(int(character))

    return weekdays


# ============================================================
# MAIN QUEUE GENERATOR
# ============================================================

def generate_queue():

    print("=" * 70)
    print("AIRFAREX - VALID FARE SEARCH QUEUE")
    print("=" * 70)

    print(f"\nInput file : {INPUT_FILE}")
    print(f"Output file: {OUTPUT_FILE}")

    # --------------------------------------------------------
    # Check input
    # --------------------------------------------------------

    if not INPUT_FILE.exists():
        print("\nERROR: Could not find DGCA routes file.")
        print(f"Expected location:\n{INPUT_FILE}")
        return

    # --------------------------------------------------------
    # Load routes
    # --------------------------------------------------------

    routes = pd.read_csv(INPUT_FILE)

    print(f"\nLoaded {len(routes)} DGCA route records.")

    # --------------------------------------------------------
    # Normalize column names
    # --------------------------------------------------------

    routes.columns = [
        str(column).strip().lower().replace(" ", "_")
        for column in routes.columns
    ]

    required_columns = [
        "origin",
        "destination",
        "frequency",
        "effective_from",
        "effective_to"
    ]

    missing = [
        column
        for column in required_columns
        if column not in routes.columns
    ]

    if missing:
        print("\nERROR: Missing required columns:")
        print(missing)
        print("\nAvailable columns:")
        print(list(routes.columns))
        return

    # --------------------------------------------------------
    # TODAY
    # --------------------------------------------------------

    today = datetime.now().date()

    print(f"Today      : {today}")
    print(f"Search dates: T+{SEARCH_WINDOWS}")

    # --------------------------------------------------------
    # Generate valid searches
    # --------------------------------------------------------

    jobs = []

    for _, route in routes.iterrows():

        origin = str(route["origin"]).strip().upper()
        destination = str(route["destination"]).strip().upper()

        if not origin or not destination:
            continue

        # Don't search invalid route
        if origin == "NAN" or destination == "NAN":
            continue

        # Parse effective dates
        effective_from = parse_date(route["effective_from"])
        effective_to = parse_date(route["effective_to"])

        # If effective_from is invalid, skip
        if effective_from is None:
            continue

        # If effective_to is missing, allow the route
        # through the search horizon.
        if effective_to is None:
            effective_to = today + timedelta(days=max(SEARCH_WINDOWS))

        # Parse operating frequency
        weekdays = parse_frequency(route["frequency"])

        # Never assume daily operation if frequency is missing
        if not weekdays:
            continue

        # ----------------------------------------------------
        # Create T+1, T+7, T+15, T+30, T+45 searches
        # ----------------------------------------------------

        for window in SEARCH_WINDOWS:

            travel_date = today + timedelta(days=window)

            # Safety check: NEVER create past-date searches
            if travel_date <= today:
                continue

            # Route must be active on travel date
            if travel_date < effective_from:
                continue

            if travel_date > effective_to:
                continue

            # Check DGCA operating weekday
            #
            # Python weekday:
            # Monday = 0
            # Sunday = 6
            #
            # DGCA:
            # Monday = 1
            # Sunday = 7

            dgca_weekday = travel_date.weekday() + 1

            if dgca_weekday not in weekdays:
                continue

            # ------------------------------------------------
            # Build job
            # ------------------------------------------------

            job = {
                "origin": origin,
                "destination": destination,
                "travel_date": travel_date.isoformat(),
                "search_window_days": window,
            }

            # Preserve useful DGCA information
            if "airline" in routes.columns:
                job["airline"] = route["airline"]

            if "flight_number" in routes.columns:
                job["flight_number"] = route["flight_number"]

            if "operator_code" in routes.columns:
                job["operator_code"] = route["operator_code"]

            if "aircraft_type" in routes.columns:
                job["aircraft_type"] = route["aircraft_type"]

            if "frequency" in routes.columns:
                job["frequency"] = route["frequency"]

            if "effective_from" in routes.columns:
                job["effective_from"] = route["effective_from"]

            if "effective_to" in routes.columns:
                job["effective_to"] = route["effective_to"]

            jobs.append(job)

    # ========================================================
    # CREATE DATAFRAME
    # ========================================================

    queue = pd.DataFrame(jobs)

    if queue.empty:

        print("\nNo valid future fare-search jobs were generated.")

        # Create an empty CSV with useful columns
        empty_columns = [
            "origin",
            "destination",
            "travel_date",
            "search_window_days",
            "airline",
            "flight_number",
            "operator_code",
            "aircraft_type",
            "frequency",
            "effective_from",
            "effective_to"
        ]

        pd.DataFrame(columns=empty_columns).to_csv(
            OUTPUT_FILE,
            index=False
        )

        return

    # ========================================================
    # REMOVE DUPLICATES
    # ========================================================

    before = len(queue)

    queue = queue.drop_duplicates(
        subset=[
            "origin",
            "destination",
            "travel_date"
        ]
    )

    after = len(queue)

    # ========================================================
    # FINAL SAFETY FILTER
    # ========================================================

    queue["travel_date_parsed"] = pd.to_datetime(
        queue["travel_date"],
        errors="coerce"
    ).dt.date

    queue = queue[
        queue["travel_date_parsed"] > today
    ]

    queue = queue.drop(columns=["travel_date_parsed"])

    # ========================================================
    # SORT
    # ========================================================

    queue = queue.sort_values(
        by=[
            "travel_date",
            "origin",
            "destination"
        ]
    )

    queue = queue.reset_index(drop=True)

    # ========================================================
    # SAVE
    # ========================================================

    queue.to_csv(
        OUTPUT_FILE,
        index=False
    )

    # ========================================================
    # SUMMARY
    # ========================================================

    print("\n" + "=" * 70)
    print("QUEUE GENERATION COMPLETE")
    print("=" * 70)

    print(f"\nOriginal DGCA routes       : {len(routes)}")
    print(f"Generated valid jobs       : {len(jobs)}")
    print(f"Duplicates removed         : {before - after}")
    print(f"Final fare-search jobs     : {len(queue)}")

    print("\nSearch dates generated:")

    print(
        queue[
            [
                "origin",
                "destination",
                "travel_date",
                "search_window_days"
            ]
        ].head(20).to_string(index=False)
    )

    print(f"\nSaved to:")
    print(OUTPUT_FILE)

    print("\nNo past dates are included.")
    print("=" * 70)


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    generate_queue()